INSERT INTO stocks (symbol, company_name, current_price, volatility_tier) VALUES

-- STABLE
('AAPL', 'Apple Inc.', 185.50, 'STABLE'),
('MSFT', 'Microsoft Corporation', 410.20, 'STABLE'),
('GOOGL', 'Alphabet Inc.', 142.75, 'STABLE'),
('AMZN', 'Amazon.com Inc.', 178.40, 'STABLE'),
('META', 'Meta Platforms Inc.', 495.60, 'STABLE'),
('JNJ', 'Johnson & Johnson', 162.10, 'STABLE'),
('PG', 'Procter & Gamble Co.', 168.25, 'STABLE'),
('KO', 'Coca-Cola Company', 61.90, 'STABLE'),
('PEP', 'PepsiCo Inc.', 173.45, 'STABLE'),
('WMT', 'Walmart Inc.', 70.30, 'STABLE'),
('COST', 'Costco Wholesale Corp.', 720.80, 'STABLE'),
('MCD', 'McDonald’s Corporation', 292.10, 'STABLE'),
('DIS', 'Walt Disney Company', 108.75, 'STABLE'),
('HD', 'Home Depot Inc.', 355.20, 'STABLE'),
('V', 'Visa Inc.', 274.60, 'STABLE'),
('MA', 'Mastercard Inc.', 465.10, 'STABLE'),
('ORCL', 'Oracle Corporation', 132.45, 'STABLE'),

-- NORMAL
('NVDA', 'NVIDIA Corporation', 890.55, 'NORMAL'),
('TSLA', 'Tesla Inc.', 245.30, 'NORMAL'),
('NFLX', 'Netflix Inc.', 610.75, 'NORMAL'),
('ADBE', 'Adobe Inc.', 525.60, 'NORMAL'),
('CRM', 'Salesforce Inc.', 305.20, 'NORMAL'),
('INTC', 'Intel Corporation', 38.95, 'NORMAL'),
('AMD', 'Advanced Micro Devices', 172.10, 'NORMAL'),
('PYPL', 'PayPal Holdings Inc.', 66.40, 'NORMAL'),
('UBER', 'Uber Technologies Inc.', 78.35, 'NORMAL'),
('LYFT', 'Lyft Inc.', 19.20, 'NORMAL'),
('SQ', 'Block Inc.', 82.10, 'NORMAL'),
('SHOP', 'Shopify Inc.', 74.60, 'NORMAL'),
('SPOT', 'Spotify Technology', 312.45, 'NORMAL'),
('TWLO', 'Twilio Inc.', 59.30, 'NORMAL'),
('SNOW', 'Snowflake Inc.', 178.50, 'NORMAL'),
('ROKU', 'Roku Inc.', 71.25, 'NORMAL'),
('DOCU', 'DocuSign Inc.', 56.80, 'NORMAL'),

-- VOLATILE
('COIN', 'Coinbase Global Inc.', 228.10, 'VOLATILE'),
('RIOT', 'Riot Platforms Inc.', 14.35, 'VOLATILE'),
('MARA', 'Marathon Digital Holdings', 18.90, 'VOLATILE'),
('PLTR', 'Palantir Technologies', 26.45, 'VOLATILE'),
('SOFI', 'SoFi Technologies', 8.60, 'VOLATILE'),
('LCID', 'Lucid Group Inc.', 3.85, 'VOLATILE'),
('RIVN', 'Rivian Automotive Inc.', 12.40, 'VOLATILE'),
('BB', 'BlackBerry Limited', 4.10, 'VOLATILE'),
('GME', 'GameStop Corp.', 23.70, 'VOLATILE'),
('AMC', 'AMC Entertainment Holdings', 4.65, 'VOLATILE'),
('BYND', 'Beyond Meat Inc.', 9.15, 'VOLATILE'),
('OPEN', 'Opendoor Technologies', 2.45, 'VOLATILE'),
('NKLA', 'Nikola Corporation', 0.95, 'VOLATILE'),
('FUBO', 'FuboTV Inc.', 1.85, 'VOLATILE'),
('CLOV', 'Clover Health Investments', 1.25, 'VOLATILE'),
('QS', 'QuantumScape Corp.', 6.80, 'VOLATILE'),
('IONQ', 'IonQ Inc.', 11.50, 'VOLATILE');